### PR TITLE
Form tags

### PR DESCRIPTION
**Pull request by TheConObs**
Updates form_for / form_tag to form_with.

### CODE REVIEW

**Comment by TheConObs** [comment]
I don't have permission to view the issues that are apparently coming up under snyk. What's happening?

**Comment by veganstraightedge** [comment]
@TheConObs Don't worry about them. Unfortunately they are upstream issues that we don't control. :/

**Comment by GeoffFoley** [comment]
Ok, the damned color-list variable. I'll fix as soon as I'm home.

**Comment by guitsaru** [comment]
Are the `PGDATA` files related to this PR?  There's a lot of newly created binary files.

**Comment by guitsaru** [comment]
@veganstraightedge any idea why the heroku status check hasn't reported yet?

**Comment by astronaut-wannabe** [comment]
@guitsaru I noticed that seems to happen whenever the PR is across forks (as opposed to across branches)

**Comment by just1602** [comment]
Yeah,if I remember well, when you're not in the team and cannot branch or push directly to the project, @veganstraightedge has to lunch the deployment manually.

**Comment by guitsaru** [comment]
Ah, yep, that makes sense.

**Comment by GeoffFoley** [comment]
I found that it was set to true globally, although I don’t remember the file name at the moment, so I removed it from forms that I could but IIRC some forms were still set up in a way that they stopped working if I took it out.

I’m not sure why that was happening as I’m new to Rails.

**Comment by veganstraightedge** [comment]
Thanks for diving into this one @TheConObs! And sorry the process took so long.

**Pull request merged**
