### PR TITLE
[TCE] Un-modal video #1924

### PR DESCRIPTION
**Pull request by QueerSynd**
From [#1924](https://github.com/crimethinc/website/issues/1924)

**Outcome**
- Removed fancybox and JQuery from the page. 
- Removed the "Watch Video" button and it's translations (as discussed, the "Download PDF" button is left alone, centered).
- Moved the video in an iframe right in a new section below the titles.

| Width        | Screenshot           |
| ------------- |:-------------:|
|   1200px+   |   |
| 914px     |     |
| 686px      |  |
| 500px |    |

We should discuss the size and positioning of the video on various breakpoints, I just did it as a proposition as I am not sure what you might actually have in mind for smaller devices for example 😄 

**PS**: Sorry for the commits from other issues tagging along, I wasn't expecting them to show up after merging and pulling on my side. Will avoid the issue next time

### CODE REVIEW

**Comment by veganstraightedge** [comment]
@QueerSynd Great start! Thanks for digging into this. Here are my thoughts about how to handle the different breakpoints:

**Video max width**, even at a larger window width: **1285px**

**Spacing around the video** in the black row: **at least 30px**, but maybe up to 50-100px vertically. We'll need to feel it out.

For **Download PDF**, let's try either:

1. Dropping the round rect and instead jump straight to the full width translucent white bar
2. Make the round rect only as big as the area of _Download PDF_, not `display: block` / full width

***

Does that all make sense?

Let's give those a try and see how it looks behaves then.

**Comment by veganstraightedge** [comment]
@QueerSynd If you'd like to be added to our Slack, send an email to tech at our domain dot com with the email address that you want to be invited at.

**Comment by QueerSynd** [comment]
Thanks for the feedback @astronaut-wannabe !

I just pushed the first solution **Download PDF** background, I think it is the most elegant of both. 

On the breakpoints though I am not sure I get it well:
> **Video max width**, even at a larger window width: **1285px**
> 
> **Spacing around the video** in the black row: **at least 30px**, but maybe up to 50-100px vertically. We'll need to feel it out.

I can set a max width, but the video being in an iframe, the size of the video is actually controlled by its height. What I can do is give the iframe a margin of 30px (even on smaller breakpoints? the video might be very small at this point), and control the height. I would propose something like that:

```css
max-width: 1285px;
height: 40vh;

@media (min-width: 576px) {
  height: 50vh;
}

@media (min-width: 900px) {
  height: 70vh;
}

@media (min-width: 1200px) {
  height: 95vh;
}
```
The place of the margin is left to be defined on my side.

what do you think?

**Comment by QueerSynd** [comment]
Zsdert67uhbn

**Comment by QueerSynd** [comment]
I committed the code as I suggested above.
I think this can be merged if there are no bugs, and we could open another ticket to define the size of the video precisely. What do you think?

**Comment by veganstraightedge** [comment]
Ok, @QueerSynd. I merged the CSS listing PR. Would you mind rebasing this one, please? And then we can get it merged in too. 🎉

**Comment by QueerSynd** [comment]
As you can see with the tones of commits, I've rebased @veganstraightedge 😅 I double checked quickly, the TCE page still looks as expected, but maybe you want to have a quick look too before merging.

**Comment by veganstraightedge** [comment]
@QueerSynd Did you merge `main` into your branch or did you rebase your branch off of `main`? It's a subtle difference.

**Comment by QueerSynd** [comment]
I rebased my branch, and github was still having conflicts for whatever reason, so I solved them (which is the last commit)

**Pull request closed without merging**
