### PR TITLE
[TCE] pull images into a view partial

### PR DESCRIPTION
**Pull request by astronaut-wannabe**
As I was working on #582 I noticed the korean version has a lot of localized images.

I pulled out the image block as a partial so that:

1) I could easily override `base_url` for local development
2) resolve the slight variations among the sections

I noticed that some of the sections (listed below) are missing various `xyz-size@2x` images

Should I create these missing variations, or should a do something like this:
screen shot 2017-12-20 at 7 02 42 pm

## missing images
<details>
<summary>checklist of missing images</summary>

### power
- [X] https://cloudfront.crimethinc.com/tce/images/power-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/power-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/power-large@2x.jpg
### relationships
- [X] https://cloudfront.crimethinc.com/tce/images/relationships-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/relationships-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/relationships-large@2x.jpg
### liberation
- [X] https://cloudfront.crimethinc.com/tce/images/liberation-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/liberation-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/liberation-large@2x.jpg
### revolt
- [X] https://cloudfront.crimethinc.com/tce/images/revolt-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/revolt-small@2x.jpg
### control
- [X] https://cloudfront.crimethinc.com/tce/images/control-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/control-large@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/control-small@2x.jpg
### representation
- [X] https://cloudfront.crimethinc.com/tce/images/representation-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/representation-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/representation-large@2x.jpg
### leaders
- [X] https://cloudfront.crimethinc.com/tce/images/leaders-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/leaders-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/leaders-large@2x.jpg     
### lastcrime
- [X] https://cloudfront.crimethinc.com/tce/images/lastcrime-tablet@2x.jpg
- [X] https://cloudfront.crimethinc.com/tce/images/lastcrime-small@2x.jpg
- [ ] https://cloudfront.crimethinc.com/tce/images/lastcrime-large@2x.jpg
</details>

### CODE REVIEW

**Comment by veganstraightedge** [comment]
I think I like adding the `@2x` versions better.

**Comment by astronaut-wannabe** [comment]
@veganstraightedge here are `tablet@2x` and `small@2x` I used `large.jpg` to generate them.

Not sure how to generate the `@2x` version though

[done.zip](https://github.com/crimethinc/website/files/1577324/done.zip)

**Comment by astronaut-wannabe** [comment]
@veganstraightedge  

the base_url for TCE images is `cloudfront.crimethinc.com/tce/images/"` (no `/assets`)

so don't merge until we resolve that discrepancy

**Comment by veganstraightedge** [comment]
Oh sorry. I was conflating with this issue when I put the new images in `/assets`.

https://github.com/crimethinc/website/issues/584

**Comment by veganstraightedge** [comment]
I'll put the images in `cloudfront.crimethinc.com/tce/images` (no `/assets`) for now too.

**Comment by veganstraightedge** [comment]
Added.

**Pull request merged**
