### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by pfmag**
Um, do I need to do this? I don't know what I'm doing.

### CODE REVIEW

**Comment by astronaut-wannabe** [comment]
hey, @pfmag. whatcha trying to do? are you trying to only do the change in [` Update lit_kit.html.erb `][0]?

if so, it looks like you might have started your branch from my feature branch (which is why you are see all of my commits in your pull request)

do you have git installed on your computer, or did you make the change from the github UI?

[0]:https://github.com/crimethinc/website/pull/593/commits/a547138c4fa5e1c7788dbc20b0f7918cf7a39500

**Comment by pfmag** [comment]
Ha, I’m just trying to make that one change on that one page. I have no idea what I’m doing. I used the web UI. If you could fix it for me, or just delete whatever I’ve done that is wrong, it’d be appreciated.

**Comment by astronaut-wannabe** [comment]
@pfmag try this to see if it works for future situations (if it doesn't work, I will make the change for you)

1) go here: https://github.com/pfmag/website/edit/master/app/views/books/lit_kit.html.erb
2) make your change
3) select:  `commit directly to master`
screen shot 2017-12-22 at 3 04 42 pm
4) click the green "commit changes" button

**Comment by veganstraightedge** [comment]
Applied this in 7a8a99d44b090978e0fd6b222d4d9bcf9fb084be. 

@pfmag I'll give you a git/hub crash course anytime you want.

**Pull request closed without merging**
