### PR TITLE
Publishable Concern For Book, Poster, Logo, and Video models

### PR DESCRIPTION
**Pull request by greggawatt**

### CODE REVIEW

**Comment by veganstraightedge** [comment]
Looks good to me.

Are you going to add `Publishable` to the `Poster` and `Video` models in another PR?

**Comment by greggawatt** [comment]
This one, Just wanted to open early to get feedback

**Comment by veganstraightedge** [comment]
👍🏻 Looking good.

**Comment by veganstraightedge** [comment]
I think for clarity, it's worth naming a PR `WIP:

**Comment by veganstraightedge** [comment]
I think for clarity, it's worth naming a PR with the `[WIP]` prefix to make clear that it's not ready for review or merge. Like @astronaut-wannabe's PR https://github.com/crimethinc/website/pull/473.

The [DO NOT MERGE](https://github.com/crimethinc/website/pulls?q=is%3Apr+is%3Aopen+label%3A%22DO+NOT+MERGE%22) tag is a nice addition too. 👍🏻

**Comment by greggawatt** [comment]
Thanks for the process feedback

FYI on my branch /books is broken, seems like the seed data doesn't have the books for no-wall-they-can-build and from-democracy-to-freedom

**Comment by veganstraightedge** [comment]
Ah. Good catch. That needs to be added to seeds. I'll make an issue.

To unblock your development, you can dupe one of the other books in the db for the two that are missing. The important bit is the slug.

**Comment by greggawatt** [comment]
@veganstraightedge waiting your review, I think this can go in and then I can work on sprucing up the /tools pages with this new logic

**Comment by veganstraightedge** [comment]
Normally, I delete branches after merging the PR. But as this doesn't close the issue/s in question, I'm leaving the branch around, in case you're gonna keep working on this branch. If you're done with this branch, will you delete it please? @greggawatt

**Pull request merged**
