### PR TITLE
tweak headline shadows so they aren't cut off

### LINKED ISSUE #325: Text shadow is getting cropped
screen shot 2017-02-26 at 2 41 53 pm

On homepage story cards

### PR DESCRIPTION
**Pull request by gesa**
resolves #325 

(…also rearranges some media queries for legibility. i tested element by element to confirm my rearranging.)

<details>
<summary>some  screenshots:</summary>

## 320px
mbmyr

## 480px
9648x

## 800px
j4xba

## 1440px
tkz9e

</details>

### CODE REVIEW

**Comment by veganstraightedge** [comment]
Did you test this on:

- tag page
- archive page
- live blog / nested articles article

**Comment by gesa** [comment]
the only view this should be impacting is home, as it is namespaced to `#home`

also what is a tag page? is that the same thing as a category?

**Comment by veganstraightedge** [comment]
"should" is where developers get into trouble. Doesn't hurt to spot check test.

Tag pages are very similar to Categories.

https://crimethinc.com/categories/analysis
https://crimethinc.com/tags/j20

**Comment by gesa** [comment]
"should" as in i searched the entire codebase for the string `home` and the only place it's being applied as a css class is the body id on the home controller.

**Pull request merged**
