### PR TITLE
#394 Add the subscribtion menu to the header

### PR DESCRIPTION
**Pull request by just1602**
@veganstraightedge, it could be cool if you had some time to review the css and tell me if it's ok or if you sea a better way to do it. :)

### CODE REVIEW

**Comment by veganstraightedge** [comment]
Merged. I have additional removed /video from the nav for now to keep it to two rows of nav items.

**Comment by just1602** [comment]
But, Subscribe is to long for the design. When the width get >= 800px, than the menu get horizontal, but with the subscribe item, it's too long and the bulb logo goes under the Crimethinc. title. It takes like 810px for the bulb logo to take the right place.

Do you think we could change the $small-phone viewport width or just find a way to make the nav smaller ?

**Comment by veganstraightedge** [comment]
Really there should be a responsive menu with a hamburger icon. :/ 

Is that something you'd be up for doing if I sketch up some comps?

**Comment by just1602** [comment]
Yeah, if you have an idea on how you want it I could do it.

**Comment by veganstraightedge** [comment]
Great. I'll sketch it later today and create a new issue for you.

**Pull request merged**
