### PR TITLE
Make date form humanish

### PR DESCRIPTION
**Pull request by astronaut-wannabe**
This PR will implement #431 

---

### TODO
- [x] Native support (chrome, ff-nightly, edge, ios, android)
- [x] detect if browser needs a polyfill
- [x] polyfill support (current ff, IE, safari)
  - [x] date support
  - [x] time support
- [x] `Publish NOW!` support
- [x] Fix specs
- [x] remove `console.log()`s
- [x] Test all of the browsers
- [x] Test clicking `SAVE` with "null" input
- [x] add timezone column to all models that use `render "admin/datetime_group"`
  - [x] `app/views/admin/articles/_form.html.erb`
  - [x] `app/views/admin/episodes/_form.html.erb`
  - [x] `app/views/admin/pages/_form.html.erb`
  - [x] ` app/views/admin/videos/_form.html.erb`

## demos of current PR status

<details>
<summary>chrome (native)</summary>
<br>

current-chrome
</details>
<br>
<details>
<summary>Firefox (polyfill)</summary>
<br>

current-firefox
</details>

<br>
<details>
<summary>Safari (polyfill)</summary>
<br>

current-safari
</details>
<br>
<details>
<summary>Android </summary>

### Android Firefox

</details>
<br>

<details>
<summary>Edge (native)</summary>
<br>
 

</details>
<br>

<details>
<summary>IE 11 (polyfill)</summary>
<br>
 

</details>
<br>
<details>
<summary>iOS (native)</summary>
<br>

</details>

### CODE REVIEW

**Comment by veganstraightedge** [comment]
Looking good so far!

Two little things:

1. Do seconds have to be typed in as part of the time or can someone just type `10:00`?
2. Can you make PST the first timezone and have selected by default?

**Comment by astronaut-wannabe** [comment]
> Do seconds have to be typed in as part of the time or can someone just type 10:00?

nope, you **can** just type `hh:mm`

that firefox gif up there still doesn't have a `time` polyfill, so it is just a text box. it works, but requires it to be entered in 24-hr format. I think it will behave like the chrome gif once I find a good drop-in

> Can you make PST the first timezone and have selected by default?

 done!

**Comment by astronaut-wannabe** [comment]
so, this works, but I really don't like the `webshims` library. it seems like all-or-nothing javascript loading, and all I really want is a `time` shim.

going to keep looking for a library that is more modular

**Comment by astronaut-wannabe** [comment]
I rebased this branch so it has 2 commits:

1.  a commit of all of the database changes
2. a commit of all of the code changes

This way, if some bug is encountered, you can easily do a `git revert` on the code commit and get the old date behavior back without having to worry about database rollbacks.

---

I also attached gifs of Android (both firefox and chrome on android)

working on getting this tested in microsoft and ios

**Comment by astronaut-wannabe** [comment]
added an ios demo (includes a "publish now!" demo)

didn't have an actual phone, so used the xcode simulator

---

I think the last thing I need to check is clicking `SAVE` without and `publication_date` input.

**Comment by veganstraightedge** [comment]
This was huge! As both a PR and as an improvement to the publishing UI. Thank you so much, @astronaut-wannabe! ⭐️🌟⭐️🌟⭐️

**Pull request merged**
