### PR TITLE
Improve docsBest

### PR DESCRIPTION
**Pull request by sanmatipol**
# How does this pull request make you feel (in animated GIF format)?

alt text

# What are the relevant GitHub issues?

resolves `[link to github issue]`

# What does this pull request do?

??

# How should this be manually tested?

??

# Is there any background context you want to provide for reviewers?

??

# Questions for the pull request author (delete any that don't apply):
- [ ] Are any needed README/wiki/documentation updates needed for this pull request?
- [ ] Does the code you updated have tests? If not, could you add some please?
- [ ] Does this pull request require any new server dependencies which need to be added to the build process? If so, please explain what.

# Acceptance Criteria
## These should be checked by the reviewers

- [ ] This pull request does not cause the database export script to become out of sync with the db schema

### CODE REVIEW

**Comment by veganstraightedge** [comment]
What is this?

**Comment by sanmatipol** [comment]
> What is this?

For hactoberfest I have sended pull request
Remain pull request as it is .please

**Comment by veganstraightedge** [comment]
I don't get it. 
Can you give more context please?

**Comment by sanmatipol** [comment]
> I don't get it.
> Can you give more context please?

There is fest hactoberfest and there one condition
Is participent must have to send 4 pull request to join it.so thats why I had sended you pull request.

**Comment by just1602** [comment]
@veganstraightedge it's just spam : https://blog.domenic.me/hacktoberfest/

We should restraint contribution for october since we're gonna have a lot of spam like that.

**Pull request closed without merging**
