### PR TITLE
To Change Everything in 한국어 and english

### PR DESCRIPTION
**Pull request by astronaut-wannabe**
This is a first pass of just quickly slotting in the Korean text.

I still have a lot to do (comparing the korean web to PDF to adjust CSS, line breaks, highlights, etc)

~I also noticed translation difference between the pdf and my source files.~

~e.g.~

> ~To change anything, start everywhere.~

* ~Source files: `무엇이 든지 바꾸기 위해, 모든 곳에서 시작하자. `~
* ~The pdf:              `무엇 이든 바꾸려면 모든 곳 에서 시작하자`~

~will need to figure out how to resolve those differences~

**update**: going with the pdf for layout/language guidance 

---

### demo
https://crimethinc-staging-pr-582.herokuapp.com/tce/%ED%95%9C%EA%B5%AD%EC%96%B4

### progress screenshot
<details>
<summary> korean desktop</summary>

desktop

</details>

### CODE REVIEW

**Comment by veganstraightedge** [comment]
Looking real good. 👍🏻

**Comment by astronaut-wannabe** [comment]
@veganstraightedge @just1602  any opinions on what to do with the last panel? In english and espanol it links out to ["The Secret is to Begin"][0]

I can think of 3 options:

In languages where that article is not translated, I could...

1) link to the english version?
2) hide the last panel
3) show last panel, but it will not be a link (requires getting the phrase "the secret is to begin" translated)

[0]:https://crimethinc-staging-pr-582.herokuapp.com/2016/09/28/feature-the-secret-is-to-begin-getting-started-further-resources-frequently-asked-questions

**Comment by just1602** [comment]
@astronaut-wannabe if we keep in mind that implementation of a translation / multilanguage system is in the roadmap we could only translate the "the secret is to begin" and link it to the good translation when it'll be done?

**Comment by veganstraightedge** [comment]
> 1. link to the english version?
> 2. hide the last panel
> 3. show last panel, but it will not be a link (requires getting the phrase "the secret is to begin" translated)


I like 1 the best. It at least gives the reader the option of reading it in English or Google translating it. 

At the same time, I'll put out some feelers to get it translated into Korean.

**Comment by veganstraightedge** [comment]
Is this a copy/paste error / typo or something else?

screen shot 2017-12-26 at 12 31 36 pm

**Comment by veganstraightedge** [comment]
Do you need these words translated? If so, what words are they?
screen shot 2017-12-26 at 12 32 25 pm
screen shot 2017-12-26 at 12 32 32 pm

**Comment by veganstraightedge** [comment]
These two panels would probably read better as either white text with a little bit of black shadow or black text with a little bit of white shadow. Wanna try each and see how they look?
screen shot 2017-12-26 at 12 31 50 pm

**Comment by veganstraightedge** [comment]
@astronaut-wannabe  First "the secret is to begin" translation. We should corroborate that with a couple few folks still. But it can work as a placeholder for now. 

Translation by: @jessabean.

https://twitter.com/jessabean/status/945842524853276673

**Comment by astronaut-wannabe** [comment]
> Is this a copy/paste error / typo or something else?

no, that is the design in the pdf

> Do you need these words translated? If so, what words are they?

The first one is introduction I think. That should be safe to pull from a dictionary.

The second one is "order in bulk" and is more like the *"The Secret is to Begin"* issue. should I just hide that link in languages that do  not have a translated `/get` page? Or is it possible to make a bulk order of korean TCE prints?

> These two panels would probably read better as either white text with a little bit of black shadow or black text with a little bit of white shadow. Wanna try each and see how they look?

👍

> First "the secret is to begin" translation. We should corroborate that with a couple few folks still. But it can work as a placeholder for now.

I checked this translation with a Korean friend. They said this wording makes sense

**Comment by veganstraightedge** [comment]
> The second one is "order in bulk" and is more like the "The Secret is to Begin" issue. should I just hide that link in languages that do not have a translated /get page? Or is it possible to make a bulk order of korean TCE prints?

I'm pretty sure only en/es are available for bulk orders. 

If there isn't a /:lang/get page for that :lang, let's link to `/tce/get` (EN version) for now.

**Comment by astronaut-wannabe** [comment]
@veganstraightedge this should be good to go.

some css bugs may on the korean may come in as it is viewed on more devices, but it looked good on everything I had on me.

can you do a feature branch PR deploy for heroku so I can real quick view it in staging (to test the video link mainly)

**Pull request merged**
