### PR TITLE
Hardcode available_locales to english and spanish, for now

### PR DESCRIPTION
**Pull request by veganstraightedge**
To prevent other language failing before we have translations for them.

### CODE REVIEW

**Comment by veganstraightedge** [comment]
@guitsaru I **think** it'll only redirect to a subdomain that is:

- in this list AND
- is set by your browser as your preferred language

**Comment by guitsaru** [comment]
@veganstraightedge right, isn't that the case for pt-BR that we're trying to fix?  I just want to make sure that doesn't keep happenning.

**Comment by astronaut-wannabe** [comment]
should be ok since browsers send actual locale code (e.g. `pt-BR` whereas TCE is in a word)

**Comment by guitsaru** [comment]
@astronaut-wannabe gotcha, I thought that might be the case, but wanted to make sure.

**Pull request merged**
