### PR TITLE
Site Search

### LINKED ISSUE #36: Add site search
- basic search: one box searches all the things
  - sub/titles
  - content
  - tags
  - authors
- advanced search: one box with key value syntax (like GitHub's)
  - is:issue is:open
  - author: b.traven
  - title: police
- advanced search page: fields for each search category
  - https://twitter.com/search-advanced

### PR DESCRIPTION
**Pull request by guitsaru**
- [x] Basic Search
- [x] Advanced Search
- [x] Advanced Search Page

Searches Articles, Posts, and Episodes.

image
image
image

Closes #36

### CODE REVIEW

**Comment by guitsaru** [comment]
@veganstraightedge: What version of PostgreSQL is running on Heroku?  As written, this PR requires PostgreSQL 9.6, but I can probably get it down to 9.4 relatively easily.

**Comment by veganstraightedge** [comment]
```
crimethinc/website: h pg:info
=== DATABASE_URL
Plan:               Standard 0
Status:             Available
Data Size:          22.7 MB
Tables:             22
PG Version:         9.6.1
Connections:        12/120
Fork/Follow:        Available
Rollback:           earliest from 2017-05-15 00:22 UTC
Created:            2017-01-11 04:41 UTC
Region:             us
Maintenance:        not required
Maintenance window: Wednesdays 19:00 to 23:00 UTC
```

**Comment by veganstraightedge** [comment]
You can ignore Heroku CI failures for now. They're erroring because a Ruby version mismatch. Somehow CI is running `2.3.4`. I've got a support ticket open with Heroku.

**Comment by veganstraightedge** [comment]
@guitsaru Hey, sorry for the delay on responding to this. It looks real great!

If you fix the merge conflict (caused by my delay), I'll get it merged in.

Bonus points for these nit picky things:

- [ ] A header on the search results page that says something like: `Search results for "*SEARCH TERM*"`
- [ ] A `<title>` for that page with the same same as above item
- [ ] Only show the `Advanced Search` link on the search results page (so they have to normal text box search first, get results, then optionally click the link for advanced searchery)

Really optional SCSS things that you can skip if SCSS isn't your jam.
- [ ] use the same field styles as the subscribe text box in the site footer
- [ ] right align the search button on advanced, like the subscribe form in footer

**Comment by guitsaru** [comment]
@veganstraightedge I think I got all of those fixes in.  Let me know what you think.

**Comment by veganstraightedge** [comment]
Will you rebase / merge in master to get that seeds fix. That'll trigger a new review app build on Heroku.

**Comment by guitsaru** [comment]
👍

**Pull request merged**
