### PR TITLE
Bump ruby version to ruby 3.1

### PR DESCRIPTION
**Pull request by just1602**
# How does this pull request make you feel (in animated GIF format)?

excited person

# What does this pull request do?

It upgrades ruby to 3.1.0

# How should this be manually tested?

* Check that all the tests pass
* Check on the staging environment that everything seems to work

### CODE REVIEW

**Comment by just1602** [comment]
@veganstraightedge @astronaut-wannabe 

I'm not sure I like the new default that avoid the value in a hash if it has the same name has the key. Do you prefer I fix them or I had an exception to the rubocop config?

**Comment by veganstraightedge** [comment]
> @veganstraightedge @astronaut-wannabe
> 
> I'm not sure I like the new default that avoid the value in a hash if it has the same name has the key. Do you prefer I fix them or I had an exception to the rubocop config?

Good question! Can you point to an example of this so I can better understand, please?

**Comment by veganstraightedge** [comment]
Oh I see now. In the linter/rubocop PR check failure output.

Yeah, that's fucking weird. I propose that we disable that rule and move it into `.rubocop.yml`. Maybe in the future our brains will have adjusted to like it better, but for now, it's weird to my brain.

**Comment by just1602** [comment]
@veganstraightedge  do you think it could be possible to have a staging deployment to validate it works as expected?

**Review by veganstraightedge — APPROVED** [review]

**Pull request merged**
