### PR TITLE
Support tagging pages

### PR DESCRIPTION
**Pull request by withoutboats**
Per #71 

Current commit is just the data model change, I'll add UI in a subsequent commit to this PR.

### CODE REVIEW

**Comment by withoutboats** [comment]
This seems ready to review. It allows admins to tag pages. Those tags don't get displayed on the page, and the pages aren't displayed on the tag's page, because I'm not sure what the UI y'all want for that is.

In terms of deprecated categories and themes, it seems totally reasonable to just migrate categories to tags, since they have the same representation. I'm not sure if all the categories that exist want to still exist as tags, though; the ones that are seeded are the old categories from the earlier site, which aren't really topical.

Themes could also be migrated, though they seem to have a constraint that an article only has one theme; I don't know if this is something we want to keep.

**Comment by veganstraightedge** [comment]
Hi @withoutboats! Looks pretty good so far at quick glance.

But if I'm understanding it correctly, it's not quite ready to merge as is. Unless I'm missing something.

**Is there a way to discern that one tag is a tag and another is a category?**

***

There is no difference between the two in structure, but how we use `Category` is like sections in a newspaper. 

`Tag` is topical. There can be an _Arts_ `Article` *tagged* with "foo" and a _History_  `Article` *tagged* with "foo".

An `Article` can have many `tags`. Way more than we (currently) want to show in the header image area.

An `Article` can have many `categories`, but we keep it between 1 and 3. So we can show them in the header image area.

`Categories` are used as a top level item in the site nav (footer). `Tags` are not.

***

Am I missing how this is done?
If I'm not and it doesn't currently work that way, can you add that to your PR please?

(Sorry this Issue didn't have better specs.)

PS. `Themes` have a similar requirement. Structurally, they're very similar to `Tags` (even if we removed the one theme per `Article` restriction, which I'd be fine with.)

**Comment by withoutboats** [comment]
> Is there a way to discern that one tag is a tag and another is a category?

This doesn't actually change anything about either categories or themes - this PR only allows tags to be applied to page (so articles still have both categories and tags).

The questions in my previous comments were to suss out the requirements you've enumerated, thanks :-)

If you want we can land these changes incrementally or I can keep iterating on the other changes in #71 on this branch, it doesn't make a difference to me.

**Comment by veganstraightedge** [comment]
Oh great! I misunderstood. 

Incremental is better than all at once. I'll ask @bookis to review this PR too.

**Pull request merged**
