### PR TITLE
Related articles redesign

### PR DESCRIPTION
**Pull request by just1602**
Please, check the CSS related to the `.related-article header` since it take me a while to have well place and align title and subtiltle, but I'm not sure if it's the best way to to it.

### CODE REVIEW

**Comment by veganstraightedge** [comment]
screen shot 2017-12-28 at 8 21 43 pm

Good start, but it still needs work. Here are the issues I see:

- [ ] the whole `related articles` block is wider than the article content
- [ ] the `related articles` content is offset to the left of the `related articles` heading
- [ ] the `title` / `subtitle` is on top article header image. instead they should be underneath it. see, the "wireframe" in #583.
- [ ] the `title` / `subtitle` should be black text, on the white background of the page
- [ ] there should be more vertical space between each row of `related articles` categories

**Comment by just1602** [comment]
The `.related-articles` follow the first paragraph width. Otherwise. I fix the things you ask.

**Comment by veganstraightedge** [comment]
screen shot 2018-01-03 at 2 49 30 pm

**Comment by veganstraightedge** [comment]
It looks like the main issue you're having is that each related item has a fixed height of 200px. Some title/subtitles are taller than that. Try allowing each article block (image, title, subtitle) to be as tall as it needs to be. It's ok if each item in the row is a different height.

**Comment by veganstraightedge** [comment]
crimethinc how anti-fascists won the battles of berkeley 2017 in the bay and beyond a play-by-play analysis 2018-01-03 15-03-38

**Comment by veganstraightedge** [comment]
Looks a lot better. And now it's *very* close to done.

I think this is the last issue.

The `Related Articles` section needs a little bit of white space around it. Right now when the window is narrow (but not mobile), the titles/subtitles run right up to the edge of the window. It should behave similar to the footer. Whatever that measurement is for the padding/margin on the footer, use that.

👍🏻

**Comment by veganstraightedge** [comment]
Oops.

**Comment by veganstraightedge** [comment]
screen shot 2018-01-07 at 12 10 08 pm
screen shot 2018-01-07 at 12 10 18 pm
screen shot 2018-01-07 at 12 12 41 pm

**Pull request merged**
