### PR TITLE
Remove resize listeners on TCE page

### PR DESCRIPTION
**Pull request by QueerSynd**
As mentioned [here](https://github.com/crimethinc/website/pull/1920) I propose to remove the resize listeners and callbacks on the TCE page. The changes don't seem to affect the page layout, but I would feel more confident if someone used to the page could double check.

### CODE REVIEW

**Review by astronaut-wannabe — APPROVED** [review]
lgtm

i will merge it in and play around with it on staging

**Comment by astronaut-wannabe** [comment]
@QueerSynd i can't merge till the pr is moved from draft -> open

you ok with me doing that?

i'll click around with things in staging to see if everything looks ok, and we can always revert if something seems broken

**Comment by QueerSynd** [comment]
> @QueerSynd i can't merge till the pr is moved from draft -> open
> 
> you ok with me doing that?
> 
> i'll click around with things in staging to see if everything looks ok, and we can always revert if something seems broken

No problem

**Comment by astronaut-wannabe** [comment]
everything looks good to me :+1: 


| phone | tablet landscape | tablet portrait | desktop | gif |
|----------|------------------------|-----------------|--------------|---|
| tce-phone | tce-tablet-landscape | tce-tablet-portrait | tce-desktop | tce |

**Pull request merged**
